name: staceykane
favicon: null
layout_spectrum: 0.01301
typography_spectrum: 0.6799134097527713
title: 'Stacey Kane | Photographer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d5d3d4'
    - '#aaa8a9'
    - '#6c6c6c'
    - '#2e2e2e'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
